module "eventbridge_advance" {
  source                    = "git@github.com:jetblueairways/ccaas-terraform-modules-wrapper.git//jb-terraform-aws-eventbridge?ref=main"
  prefix_company            = "jb"
  lob                       = "itsd"
  prefix_region             = "usw2"
  application               = "recordings"
  env                       = "sandbox"
  create_bus                = true
  create_schemas_discoverer = false
  attach_tracing_policy     = false
  attach_kinesis_policy     = false
  kinesis_target_arns       = []
  attach_sfn_policy         = false
  sfn_target_arns           = []
  attach_sqs_policy         = false
  sqs_target_arns           = []
  attach_cloudwatch_policy  = false
  cloudwatch_target_arns    = []
  append_rule_postfix       = true
  attach_ecs_policy         = false
  ecs_target_arns           = []
  rules                     = {}
  targets                   = {}
  attach_policy_json        = false
  policy_json               = null
  attach_policy_jsons       = false
  policy_jsons              = []
  number_of_policy_jsons    = 0
  attach_policies           = false
  policies                  = []
  number_of_policies        = 0
  attach_policy_statements  = false
  policy_statements         = {}
  tags                      = local.tags
}
